# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fTelemetry.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x05\n\tTelemetry\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x1c\n\x14\x65nroute_positions_id\x18\x02 \x01(\t\x12\x17\n\x0fregistration_id\x18\x03 \x01(\t\x12\x18\n\x10reference_number\x18\x04 \x01(\t\x12\'\n\x08location\x18\x05 \x01(\x0b\x32\x15.Telemetry.PointModel\x12\x17\n\x0fground_speed_kt\x18\x06 \x01(\x01\x12\x15\n\rtime_measured\x18\x07 \x01(\x03\x12\x11\n\ttime_send\x18\x08 \x01(\x03\x12\x19\n\x11\x62\x61ttery_remaining\x18\t \x01(\x05\x12\x0c\n\x04mode\x18\n \x01(\t\x12\x19\n\x11\x61ltitude_ft_wgs84\x18\x0b \x01(\x01\x12#\n\x1b\x61ltitude_num_gps_satellites\x18\x0c \x01(\x05\x12\x10\n\x08hdop_gps\x18\r \x01(\x01\x12\x19\n\x11track_bearing_deg\x18\x0e \x01(\x01\x12\x41\n\x17track_bearing_reference\x18\x0f \x01(\x0e\x32 .Telemetry.TrackBearingReference\x12\x10\n\x08vdop_gps\x18\x10 \x01(\x01\x12\x0c\n\x04roll\x18\x11 \x01(\x01\x12\x0b\n\x03yaw\x18\x12 \x01(\x01\x12\r\n\x05pitch\x18\x13 \x01(\x01\x12\x11\n\tclimbrate\x18\x14 \x01(\x01\x12\x0f\n\x07heading\x18\x15 \x01(\x01\x1a\x34\n\nPointModel\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lng\x18\x03 \x01(\x01\";\n\x15TrackBearingReference\x12\x0e\n\nTRUE_NORTH\x10\x00\x12\x12\n\x0eMAGNETIC_NORTH\x10\x01\x32H\n\x0fTelemetryModule\x12\x35\n\rPostTelemetry\x12\n.Telemetry\x1a\x16.google.protobuf.Empty(\x01\x42\x1b\xaa\x02\x18\x43onformanceCommon.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Telemetry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\030ConformanceCommon.Protos'
  _globals['_TELEMETRY']._serialized_start=49
  _globals['_TELEMETRY']._serialized_end=699
  _globals['_TELEMETRY_POINTMODEL']._serialized_start=586
  _globals['_TELEMETRY_POINTMODEL']._serialized_end=638
  _globals['_TELEMETRY_TRACKBEARINGREFERENCE']._serialized_start=640
  _globals['_TELEMETRY_TRACKBEARINGREFERENCE']._serialized_end=699
  _globals['_TELEMETRYMODULE']._serialized_start=701
  _globals['_TELEMETRYMODULE']._serialized_end=773
# @@protoc_insertion_point(module_scope)
